# Generated by Django 3.2.8 on 2021-10-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='aadhaar_number',
            field=models.CharField(max_length=16),
        ),
    ]
