# Generated by Django 3.2.8 on 2021-10-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_uploadimagetest'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='s_doc'),
        ),
    ]
